public class ACETFormsHistoryResult {

    public String requestdate{get;set;}
    public String recievedDate{get;set;}
    public String documentname{get;set;}
    public integer quantity{get;set;}
    public String status{get;set;}
    public String maileddate{get;set;}
    public String recipient{get;set;}
    public String Address{get;set;}
    public String documenttype{get;set;}
    public String source{get;set;}
    public Boolean isAvailable{get;set;}
    public String statusToolTip{get;set;}
    public string recipientId{get;set;} 
    
}