public class ACETAuthorizationSearchResult {
    public string jsonString{get;set;}
    public String Case_Type_Code { set; get; }
    public String Case_Type_Desc { set; get; }
    public String Case_Reason_Code { set; get; }
    public String Case_Reason_Desc { set; get; }
    public String Authorization_Number { set; get; }
    public String Case_Status { set; get; }
    public String Primary_Diagnosis { set; get; }
    public String Pre_Determination { set; get; }
    public String Facility_Status { set; get; }
    public String Create_Date { set; get; }
    public string Admit_Date { set; get; }
    public string Dscharg_Date { set; get; }
     public string Expected_Admit_Date { set; get; }
    public string Actual_Dscharg_Date { set; get; }

    public string Actual_Admit_Date { set; get; }
    public string Expected_Dscharg_Date { set; get; }

    public String POS { set; get; }
    public String LOS { set; get; }
    public string Expected_Start_Date { set; get; }
    public string Actual_End_Date { set; get; }
    public string Actual_Start_Date { set; get; }
    public string Expected_End_Date { set; get; }
    public string Start_Date { set; get; }
    public string End_Date { set; get; }


    public String Procedure_Code { set; get; }
    public string CountCode { set; get; }
    public string CountDesc { set; get; }
    public String Count { set; get; }
    public String ServiceDescDetail { set; get; }
    public String ServiceProviderStatus { set; get; }
    public String ServiceProvider { set; get; }
    public string AuthID { set; get; }
    public Boolean selected{get;set;}
 
}