public class ACETLGT_FormsHistoryResult {
    @AuraEnabled
    public String requestdate{get;set;}
    @AuraEnabled
    public String documentname{get;set;}
    @AuraEnabled
    public integer quantity{get;set;}
    @AuraEnabled
    public String status{get;set;}
    @AuraEnabled
    public String maileddate{get;set;}
    @AuraEnabled
    public String recipient{get;set;}
    @AuraEnabled
    public String Address{get;set;}
    @AuraEnabled
    public String documenttype{get;set;}
    @AuraEnabled
    public String source{get;set;}
    @AuraEnabled
    public Boolean isAvailable{get;set;}
    @AuraEnabled
    public String statusToolTip{get;set;}
    @AuraEnabled
    public string recipientId{get;set;} 
    @AuraEnabled
    public string recievedDate{get;set;}       
    
}