public class ACETLGT_AuthorizationSearchResult {
    @Auraenabled public string jsonString{get;set;}
    @Auraenabled public String Case_Type_Code { set; get; }
    @Auraenabled public String Case_Type_Desc { set; get; }
    @Auraenabled public String Case_Reason_Code { set; get; }
    @Auraenabled public String Case_Reason_Desc { set; get; }
    @Auraenabled public String Authorization_Number { set; get; }
    @Auraenabled public String Case_Status { set; get; }
    @Auraenabled public String Primary_Diagnosis { set; get; }
    @Auraenabled public String Pre_Determination { set; get; }
    @Auraenabled public String Facility_Status { set; get; }
    @Auraenabled public String Create_Date { set; get; }
    @Auraenabled public string Admit_Date { set; get; }
    @Auraenabled public string Dscharg_Date { set; get; }
    @Auraenabled public string Expected_Admit_Date { set; get; }
    @Auraenabled public string Actual_Dscharg_Date { set; get; }
	@Auraenabled public string Actual_Admit_Date { set; get; }
    @Auraenabled public string Expected_Dscharg_Date { set; get; }
    @Auraenabled public String POS { set; get; }
    @Auraenabled public String LOS { set; get; }
    @Auraenabled public string Expected_Start_Date { set; get; }
    @Auraenabled public string Actual_End_Date { set; get; }
    @Auraenabled public string Actual_Start_Date { set; get; }
    @Auraenabled public string Expected_End_Date { set; get; }
    @Auraenabled public string Start_Date { set; get; }
    @Auraenabled public string End_Date { set; get; }
    @Auraenabled public String Procedure_Code { set; get; }
    @Auraenabled public string CountCode { set; get; }
    @Auraenabled public string CountDesc { set; get; }
    @Auraenabled public String Count { set; get; }
    @Auraenabled public String ServiceDescDetail { set; get; }
    @Auraenabled public String ServiceProviderStatus { set; get; }
    @Auraenabled public String ServiceProvider { set; get; }
    @Auraenabled public string AuthID { set; get; }
    @Auraenabled public Boolean selected{get;set;}
}