public with sharing class ACETCommunicationSearchResult {

    public boolean selectRecord{get;set;}
    public string Document_Class{get;set;}
    public string Document_Class_PRA{get; set;}
    public String Document_Class_SBC{get;set;}
    public string Document_ID{get;set;}
    public String DocumentContentType {get;set;}
    public Boolean IsDocSizeMoreThanOneMB {get;set;}
    public string Document_ID_PRA {get;set;}
    public string EOB_Date{get;set;}
    public string Document_ID_SBC{get;set;}
    public string Funding_Type{get;set;}
    public string Funding_Type_PRA{get;set;}
    public string Member_Id{get;set;}
    public string Member_Name{get;set;}
    public string organization{get;set;}
    public string policy_Number{get;set;}
    public string Check_EFT_Number{get;set;}
    public string Payee_Name{get;set;}
    public string PRA_Date{get;set;}
    public string Series_Designator{get;set;}
    public string Tax_ID{get;set;}
    public string redStatus{get;set;}
    public String redDateTime{get;set;}
    public String Member_ID_PRA{get;set;}
    public String Organization_PRA{get;set;}
    public String resend_Status{get;set;}
    public String resend_Date_Time{get;set;}
    public String Employer_Group_Name_SBC{get; set;}
    public String Organization_SBC{get; set;}
    public String Funding_Type_SBC{get; set;}
    public String Policy_End_Date_SBC{get; set;}
    public String Policy_Number_SBC{get; set;}
    public String Policy_Start_Date_SBC{get; set;}
    public String Employee_ID_Test{get; set;}
    public String Member_ID_Test{get; set;}
    public String Payee_Name_Test{get; set;}
    public String Policy_Number_Test{get; set;}
    public String Tax_ID_Test{get; set;}
    public String Organization_Test{get; set;}
    public String Funding_Type_Test{get; set;}
    public String Document_ID_Test{get; set;}

}