public without sharing class ADBMemberProgramsServiceRequestWrapper {
	public availableProgramsRequest availableProgramsRequest;
    public class availableProgramsRequest {
        public string sourceMemberId;
        public string sourceMemberIdType;
        public string xrefPartitionID;
        public string firstName;  
        public string lastName;
        public string dateOfBirth;
        public string state;
        public string memberId;
    }
}