{
	
			"issue": {
				"issueId": "D01181129265332",
				"updateDate": "2020-04-27",
				"updateTime": "11:29:26",
				"priority": "N",
				"repeatIndicator": "1",
				"contactMethodCode": "P",
				"originatorTypeCode": "EM",
				"directionCode": "I",
				"status": "H",
				"surveyCode": "",
				"callHistoryFlag": "",
				"callbackPromisedDate": "",
				"followupDate": "",
				"businessSegmentName": "HLTHADVR",
				"routeConditionCode": "00000",
				"hipaaIndicator": "N",
				"reasonCode": "ICOB",
				"reasonType": "03",
				"reasonCategory": "ELI",
				"reasonHcnasType": "",
				"subReasonText": "",
				"complaintCategoryText": "",
				"launchCategoryText": "",
				"launchReasonText": "",
				"grievanceCategoryText": "",
				"grievanceReasonText": "",
				"grievanceReasonCode": "",
				"grievanceReceiptDate": "",
				"grievanceDispositionText": "",
				"dispositionNotificationDate": "",
				"campaignCode": "",
				"campaignReportText": "",
				"pssActionTaken": "",
				"callAttemptDetailText": "",
				"callProgramName": "",
				"pharmacyClassText": "",
				"pharmacyClaimNumber": "",
				"pharmacyName": "",
				"pharmacyId": "",
				"assignedPssId": "",
				"callMeetsExpectationIndicator": "",
				"callExceedsExpectationIndicator": "",
				"disposition": "",
				"checkNumber": "",
				"seriesDesignator": "",
				"caseNumber": "",
				"payer": "",
				"member": {
					"zipCode": "55117",
					"dependentName": {
						"firstName": "TERRI",
						"lastName": "ANDERSON"
					},
					"dependentNumber": "000",
					"memberName": {
						"firstName": "TERRI",
						"lastName": "ANDERSON"
					},
					"memberNumber": "474706605",
					"groupName": "BOY SCOUTS OF AMERIC",
					"groupNumber": "3136003",
					"relationshipCode": "EE",
					"relationship": "0",
					"relationshipSequenceNumber": "001",
					"customerNumber": "1136003",
					"product": "",
					"market": "22700",
					"legalEntity": "",
					"policy": "0136003",
					"planVariationCode": "",
					"reportingCode": "",
					"alternateId": "965627902",
					"eligibilitySourceSystem": "U",
					"division": "",
					"masterGroupNumber": "",
					"faxNumber": "",
					"email": "",
					"logonId": "",
					"site": "",
					"leadPlanCode": "",
					"personalIdentificationNumber": "314582724",
					"primaryPolicyNumber": "",
					"sharedArrangementId": "00",
					"obligorId": "01",
					"eligibilityValidatedFlag": "",
					"otherSubscriberId": "",
					"statusCode": "",
					"medicareId": "",
					"medicaidId": "",
					"premiumWithholdCode": "",
					"coverageIndicator": "",
					"totalNonCoverageCount": "000",
					"subsidyOverrideIndicator": "",
					"optOutIndicator": "",
					"enrollmentSourceCode": "",
					"secondaryDrugInsuranceIndicator": "",
					"lisPctCode": "",
					"copayEffectiveDate": "",
					"ssaPaymentCode": "",
					"logoIndicator": "",
					"fontIndicator": "",
					"stateCode": "",
					"countryCode": "",
					"genderCode": "",
					"verbalLanguageName": "",
					"writtenLanguageName": "",
					"emailIndicator": "",
					"raceEthnicityCode": "",
					"dateOfBirth": "",
					"age": "000",
					"originalEffectiveDate": "",
					"assignedCsrName": "",
					"dateOfDeath": "",
					"medicareStatusCode": "",
					"dlEligIndicator": "",
					"pcpOverrideIndicator": "",
					"planCode": "",
					"benefitPackageCode": "",
					"regionCode": "",
					"ipaCode": "",
					"panelCode": "",
					"riderCodeIndicator": "",
					"riderCodes": ["", "", "", "", "", "", "", ""],
					"meetingTypeName": "",
					"meetingDate": "",
					"ambulanceIndicator": "",
					"chiropracticServiceQuoted": "",
					"cosmeticServiceQuoted": "",
					"cataractSurgeryBenefitsQuoted": "",
					"deductibleServiceQuoted": "",
					"diabeticEducationServiceQuoted": "",
					"diabeticMonitorAndSuppliesServiceQuoted": "",
					"diagnosticAndRadiologyServiceQuoted": "",
					"diagnosticLaboratoryServiceQuoted": "",
					"durableMedicalEquipmentServiceQuoted": "",
					"emergencyAndUrgentCareServiceQuoted": "",
					"familyPlanningServiceQuoted": "",
					"hearingExamServiceQuoted": "",
					"homeHealthServiceQuoted": "",
					"immunizationsServiceQuoted": "",
					"inpatientHospitalAndMedicalServiceQuoted": "",
					"inpatientMentalHealthServiceQuoted": "",
					"medicareCoveredDentalServiceQuoted": "",
					"nonRadiologyAndTherapeuticServiceQuoted": "",
					"orthoticsAndProstheticsServiceQuoted": "",
					"maxOutOfPocketQuoted": "",
					"outpatientSurgeryAndObservationServiceQuoted": "",
					"outpatientMentalHealthServiceQuoted": "",
					"outpatientRehabilitationServiceQuoted": "",
					"passportIndicator": "",
					"pcpOfficeVisitServiceQuoted": "",
					"preventiveScreeningServiceQuoted": "",
					"csrProgramServiceQuoted": "",
					"renalDialysisServiceQuoted": "",
					"skilledNursingServiceQuoted": "",
					"transplantServiceQuoted": "",
					"specialistOfficeVisitServiceQuoted": "",
					"oonBenefitServiceQuoted": "",
					"visionBenefitServiceQuoted": "",
					"bloodServiceQuoted": "",
					"podiatryBenefitsServiceQuoted": "",
					"alternativeAndHolisticMedicineServiceQuoted": "",
					"careManagementProgramServiceQuoted": "",
					"custodialCareServiceQuoted": "",
					"valueAddedServiceServiceQuoted": "",
					"dentalServiceQuoted": "",
					"healthyLivingProgramsServiceQuoted": "",
					"hearingServiceQuoted": "",
					"gymMembershipServiceQuoted": "",
					"otcSuppliesServiceQuoted": "",
					"transportationServiceQuoted": "",
					"riderBenefitsServiceQuoted": "",
					"memberMeetingsServiceQuoted": "",
					"brandDrugsServiceQuoted": "",
					"genericDrugsServiceQuoted": "",
					"mailOrderServiceQuoted": "",
					"maxLimitationsServiceQuoted": "",
					"partBDrugsServiceQuoted": "",
					"pharmacyLocatorServiceQuoted": "",
					"preferredFormularyServiceQuoted": "",
					"unfundedProgramsServiceQuoted": "",
					"trueOopServiceQuoted": "",
					"clientCode": "",
					"networkPrefixCode": "",
					"memberVerifiedIndicator": "",
					"facetPlanCode": "",
					"otherProduct": "",
					"otherGroupNumber": "0",
					"infNum": "1136003"
				},
				"claim": {
					"totalAmount": "0.00",
					"authorization": "",
					"claimNumber": "0000000000",
					"invoiceNumber": "",
					"serviceDate": "",
					"filmNumber": "000000000000000000",
					"filmSystem": "",
					"filmOffice": "",
					"payLocationNumber": "151",
					"engineCode": "C",
					"claimApp": "",
					"claimAppSsn": "000000000",
					"claimOffice": "000",
					"claimOfficeName": "0",
					"fundingArrangement": ""
				},
				"originator": {
					"dialedId": "0000000000",
					"autoId": "0000000000",
					"icrCallLocationId": "",
					"icrCallLocationDay": "",
					"originatorMpin": "000000000000",
					"originatorTin": "",
					"originatorTinSuffix": "",
					"callerAddress": {
						"street1": "305 COTTAGE AVE W, APT #312",
						"city": "ST PAUL",
						"state": "MN",
						"zip": "55117",
						"zip4": ""
					},
					"callerName": {
						"firstName": "TERRI",
						"lastName": "ANDERSON"
					},
					"dayPhone": {
						"areaCode": "651",
						"number": "2141267",
						"extension": "0000"
					},
					"eveningPhone": {
						"areaCode": "000",
						"number": "0000000",
						"extension": "0000"
					}
				},
				"provider": {
					"productCode": "",
					"panelNumber": "",
					"contractNumber": "0",
					"ipa": "00000",
					"marketSegmentName": "",
					"serviceMarket": "",
					"serviceZip": "00000",
					"providerSourceSystem": "",
					"providerValidatedFlag": "",
					"pcpValidatedFlag": "",
					"stateIssuedID": "",
					"languageCode": "",
					"originalEffectiveDate": "",
					"statusCode": "",
					"emailIndicator": "",
					"otherIpa": "",
					"pcp": {
						"firstInitial": "",
						"lastName": "",
						"mpin": "000000000",
						"mpinSequenceNumber": "000",
						"taxPrefix": "",
						"taxId": "000000000",
						"taxSuffix": "00000",
						"state": "",
						"zip": "00000"
					},
					"provider": {
						"firstInitial": "",
						"lastName": "",
						"mpin": "000000000",
						"mpinSequenceNumber": "000",
						"taxPrefix": "",
						"taxId": "000000000",
						"taxSuffix": "00000",
						"state": "",
						"zip": "0"
					}
				},
				"other": {
					"incompleteFlag": "N",
					"qaCategory": "",
					"qaCodeType": "",
					"qaSource": "",
					"qitType": "",
					"company": "C",
					"lineType": "",
					"insuranceCompany": "",
					"complState": ""
				},
				"employerInfo": {
					"employerNumber": "",
					"employerName": "",
					"employerState": ""
				},
				"serviceRequest": {
					"srProductType": "MD",
					"srType": "",
					"srSubType": "",
					"resolutionCode": "",
					"clientId": "",
					"subCodeId": "",
					"productId": "",
					"diamondProviderLocationId": "",
					"diamondProviderLocationName": "",
					"originatorLocationId": "",
					"claimAdjustmentRequiredIndicator": "",
					"addressUpdateRequiredIndicator": "",
					"wbxUpdateRequiredIndicator": "",
					"bulkCheckIndicator": "",
					"memberPhoneNumber": "",
					"memberAreaCode": "",
					"memberCity": "",
					"memberStreet1": "",
					"memberStreet2": "",
					"parentGroupName": "",
					"pcpFirstName": "",
					"pcpLastName": "",
					"pcpProviderID": "",
					"hippaEligibleFlag": "",
					"providerFirstName": "",
					"providerLastName": "",
					"providerPhoneNumber": "",
					"providerAreaCode": "",
					"providerCounty": "",
					"checkPayee": "",
					"checkStockNumber": "",
					"commonProviderId": "",
					"originalProviderId": "",
					"providerStreet1": "",
					"providerStreet2": "",
					"providerCity": "",
					"policyNumber": "",
					"dayExtensionNew": "0",
					"documentControlNumber": "",
					"closeOfficeNumber": "0",
					"closeDepartmentCode": "",
					"closeTeamCode": "",
					"lastUpdateOpid": ""
				},
				"priorityDescription": "NORMAL PRIORITY",
				"contactMethodDescription": "PHONE",
				"originatorTypeDescription": "MEMBER",
				"statusDescription": "HOLD",
				"callRequired": "N",
				"contactReasonDescription": "COB                      ",
				"detailComments": [{
						"headerNumber": "0999",
						"commentNumber": "0000",
						"type": "NW",
						"date": "2020-04-27",
						"time": "11:29:26",
						"text": "ORS SYSTEM SYSTEMS (LOCAL) RNEST SOS CHARLI ANNUNZIATA ",
						"userId": "673C98"
					}, {
						"headerNumber": "0999",
						"commentNumber": "0001",
						"type": "EN",
						"date": "2020-04-27",
						"time": "11:29:26",
						"text": "{{** OTHER SECTION: BUSINESS ALERTS VIEWED FOR TERRI ANDERSON ON 04/27/",
						"userId": ""
					}, {
						"headerNumber": "0999",
						"commentNumber": "0002",
						"type": "EN",
						"date": "2020-04-27",
						"time": "11:29:26",
						"text": "2020  **}}                                                             ",
						"userId": ""
					}
				],
				"followupStatusCode": "O",
				"followupStatusDescription": "OPEN",
				"followupPurposeCode": "H",
				"followupPurposeDescription": "HA - Eligibility Correction",
				"originatedDate": "2020-04-27",
				"owners": [{
						"officeId": "673",
						"associateId": "C98",
						"departmentCode": "SYS",
						"teamCode": "SOS",
						"associateName": {
							"firstName": "CHARLI",
							"lastName": "ANNUNZIATA"
						},
						"officeName": "ORS SYSTEM",
						"departmentName": "SYSTEMS (LOCAL)",
						"teamName": "RNEST SOS",
						"type": "Current",
						"headerNumber": "0999"
					}, {
						"officeId": "673",
						"associateId": "C98",
						"departmentCode": "SYS",
						"teamCode": "SOS",
						"associateName": {
							"firstName": "CHARLI",
							"lastName": "ANNUNZIATA"
						},
						"officeName": "",
						"departmentName": "SYSTEMS (LOCAL)",
						"teamName": "RNEST SOS",
						"type": "Original",
						"headerNumber": "0999"
					}
				],
				"message": "P",
				"messageMail": "N",
				"designeeId": "",
				"reopenFlag": "N",
				"networkCloseReason": "",
				"reasonDescription": "COB",
				"linkExists": "N"
			}
		}
	